import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { MachineService } from '../../services/machine.service';
import { ReportingFilter, ReportingService, ReconciliationReport } from '../../services/reporting.service';
import { ReportPageBase } from './report-page.base';
import { ReportFiltersComponent } from './report-filters.component';

@Component({ selector: 'app-reconciliation-report', standalone: true, imports: [CommonModule, ReportFiltersComponent], template: `
<div class="mb-5 flex items-center justify-between"><h1 class="text-2xl font-semibold text-slate-800">Nayax Reconciliation</h1><div class="flex gap-2"><button class="rounded-md border px-3 py-2 text-sm" (click)="export('csv','reconciliation')">Export CSV</button><button class="rounded-md border px-3 py-2 text-sm" (click)="export('xlsx','reconciliation')">Export XLSX</button></div></div>
<app-report-filters [from]="from" [to]="to" [machineId]="machineId" [machines]="machines" [period]="period" (fromChange)="from=$event" (toChange)="to=$event" (machineChange)="machineId=$event" (periodChange)="selectPeriod($event)" (apply)="load()" />
@if (loading) { <div class="rounded-xl bg-white p-8 text-center text-slate-500">Loading report...</div> } @else if (error) { <div class="rounded-xl bg-red-50 p-6 text-red-700">{{ error }}</div> } @else if (report) {
@if (quality().length) { <div class="mb-4 rounded-lg bg-amber-50 p-3 text-xs text-amber-800">@for (note of quality(); track note) { <div>{{ note }}</div> }</div> }
<div class="mb-5 grid gap-4 md:grid-cols-3">
  <div class="rounded-xl bg-white p-5 shadow-sm"><div class="text-sm font-semibold text-slate-500">Total Vending Sales</div><strong class="text-2xl text-slate-800">{{ money(report.totalVendingSales) }}</strong><div class="mt-2 text-sm text-slate-500">Card {{ money(report.cardSales) }} · Cash {{ money(report.cashSales) }}<br>{{ report.totalTransactionCount }} transactions</div></div>
  <div class="rounded-xl bg-white p-5 shadow-sm"><div class="text-sm font-semibold text-slate-500">Card Sales Reconciliation</div><div class="mt-1 text-sm">Recorded card sales <strong>{{ money(report.cardTransactionSales) }}</strong></div><div class="text-sm">Nayax reported gross <strong>{{ money(report.nayaxReportedGrossCardSales) }}</strong></div><div class="text-sm">Difference <strong>{{ money(report.grossDifference) }}</strong></div><span class="mt-2 inline-block rounded px-2 py-1 text-sm font-semibold" [ngClass]="statusClass(report.grossStatus)">{{ report.grossStatus }}</span></div>
  <div class="rounded-xl bg-white p-5 shadow-sm"><div class="text-sm font-semibold text-slate-500">Nayax Settlement Reconciliation</div><div class="mt-1 text-sm">Expected net <strong>{{ money(report.expectedNetReimbursement) }}</strong></div><div class="text-sm">Actual net reimbursement <strong>{{ money(report.actualNetReimbursement) }}</strong></div><div class="text-sm">Difference <strong>{{ money(report.settlementDifference) }}</strong></div><span class="mt-2 inline-block rounded px-2 py-1 text-sm font-semibold" [ngClass]="statusClass(report.settlementStatus)">{{ report.settlementStatus }}</span></div>
</div>
<div class="mb-5 overflow-x-auto rounded-xl bg-white shadow-sm"><table class="min-w-full text-sm"><thead><tr class="bg-slate-50 text-left"><th class="px-4 py-3">Period</th><th class="px-4 py-3">Vending sales</th><th class="px-4 py-3">Card sales</th><th class="px-4 py-3">Nayax gross card</th><th class="px-4 py-3">Gross difference</th><th class="px-4 py-3">Fees (ex GST)</th><th class="px-4 py-3">Fee GST</th><th class="px-4 py-3">Other fees</th><th class="px-4 py-3">Expected net</th><th class="px-4 py-3">Actual net</th><th class="px-4 py-3">Settlement</th><th class="px-4 py-3">Status</th></tr></thead><tbody>
@for (row of report.periodRows; track row.from + row.to) { <tr class="border-t align-top"><td class="px-4 py-3">{{ row.from | date:'dd/MM/yyyy' }} – {{ row.to | date:'dd/MM/yyyy' }}<div class="text-xs text-slate-500">{{ row.payoutDate ? ('Payout ' + (row.payoutDate | date:'dd/MM/yyyy')) : 'Payout pending' }}</div></td><td class="px-4 py-3">{{ money(row.totalVendingSales) }}<div class="text-xs text-slate-500">{{ row.totalTransactionCount }} transactions · {{ row.cashTransactionCount }} cash</div></td><td class="px-4 py-3">{{ money(row.cardTransactionSales) }}<div class="text-xs text-slate-500">{{ row.cardTransactionCount }} card transactions</div></td><td class="px-4 py-3">{{ money(row.nayaxReportedGrossCardSales) }}<div class="text-xs text-slate-500">{{ row.nayaxReportedCardTransactionCount }} transactions</div></td><td class="px-4 py-3">{{ money(row.grossDifference) }}<div class="text-xs" [ngClass]="statusClass(row.grossStatus)">{{ row.grossStatus }}</div></td><td class="px-4 py-3">{{ money(row.processingFeesExGst) }}</td><td class="px-4 py-3">{{ money(row.feeGst) }}</td><td class="px-4 py-3">{{ money(row.otherFees) }}</td><td class="px-4 py-3">{{ money(row.expectedNetReimbursement) }}</td><td class="px-4 py-3">{{ money(row.actualNetReimbursement) }}</td><td class="px-4 py-3">{{ money(row.settlementDifference) }}<div class="text-xs" [ngClass]="statusClass(row.settlementStatus)">{{ row.settlementStatus }}</div></td><td class="px-4 py-3 font-semibold" [ngClass]="statusClass(row.status)">{{ row.status }}</td></tr> }
</tbody>@if (report.totals) { <tfoot><tr class="border-t-2 bg-slate-50 font-semibold"><td class="px-4 py-3">Total</td><td class="px-4 py-3">{{ money(report.totals.totalVendingSales) }}</td><td class="px-4 py-3">{{ money(report.totals.cardTransactionSales) }}</td><td class="px-4 py-3">{{ money(report.totals.nayaxReportedGrossCardSales) }}</td><td class="px-4 py-3">{{ money(report.totals.grossDifference) }}</td><td class="px-4 py-3">{{ money(report.totals.processingFeesExGst) }}</td><td class="px-4 py-3">{{ money(report.totals.feeGst) }}</td><td class="px-4 py-3">{{ money(report.totals.otherFees) }}</td><td class="px-4 py-3">{{ money(report.totals.expectedNetReimbursement) }}</td><td class="px-4 py-3">{{ money(report.totals.actualNetReimbursement) }}</td><td class="px-4 py-3">{{ money(report.totals.settlementDifference) }}</td><td class="px-4 py-3" [ngClass]="statusClass(report.totals.status)">{{ report.totals.status }}</td></tr></tfoot> }</table></div>
<div class="rounded-xl bg-white p-5 shadow-sm"><div class="grid gap-3 text-sm md:grid-cols-5"><div>Processing fees ex GST<strong class="block">{{ money(report.processingFeesExGst) }}</strong></div><div>Fee GST<strong class="block">{{ money(report.feeGst) }}</strong></div><div>Other fees<strong class="block">{{ money(report.otherFees) }}</strong></div><div>Adjustments<strong class="block">{{ money(report.adjustments) }} <span class="text-xs font-normal text-slate-500">{{ report.adjustmentsSupported ? '' : '(unsupported)' }}</span></strong></div><div>Overall status<strong class="block" [ngClass]="statusClass(report.status)">{{ report.status }}</strong></div></div></div>
}
` })
export class ReconciliationReportComponent extends ReportPageBase<ReconciliationReport> {
  constructor(route: ActivatedRoute, reports: ReportingService, machines: MachineService) { super(route, reports, machines); }
  request(filter: ReportingFilter): Observable<ReconciliationReport> { return this.reports.reconciliation(filter); }
  statusClass(status: string): string {
    return status === 'Reconciled' ? 'text-emerald-700' : status === 'Mismatch' ? 'text-red-700' : 'text-amber-700';
  }
}
