// <auto-generated />
using System;
using InventoryApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913005745_AddSupplierOrders")]
    partial class AddSupplierOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("InventoryApi.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("InventoryApi.Models.CommissionPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<long>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "PeriodStart", "PeriodEnd");

                    b.ToTable("CommissionPayments");
                });

            modelBuilder.Entity("InventoryApi.Models.ImportedDevicePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportedReimbursementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentMethodDescription")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ProcessingFees")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("RawAttributesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecognitionDescription")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SalesCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ServiceFees")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TotalSum")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ImportedReimbursementId");

                    b.ToTable("ImportedDevicePayments");
                });

            modelBuilder.Entity("InventoryApi.Models.ImportedFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AverageFeeAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("FeeTypeDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeesTypeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportedReimbursementId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPreviousPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsService")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawAttributesJson")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalCount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TotalSum")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TotalSumWithVat")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("VatPercentage")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ImportedReimbursementId");

                    b.ToTable("ImportedFees");
                });

            modelBuilder.Entity("InventoryApi.Models.ImportedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileHash")
                        .IsUnique();

                    b.ToTable("ImportedFiles");
                });

            modelBuilder.Entity("InventoryApi.Models.ImportedPaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BillingProvider")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportedReimbursementId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNayaxReimbursement")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPreviousPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentMethodDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethodId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawAttributesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecognitionDescription")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalSalesCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalSalesSum")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ImportedReimbursementId");

                    b.ToTable("ImportedPaymentMethods");
                });

            modelBuilder.Entity("InventoryApi.Models.ImportedReimbursement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveDevices")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DistributorActorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErpId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinanceEntityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportedFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvoicePaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoicePaymentMethodId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInvoice")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReimbursement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawAttributesJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReimbursementEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReimbursementPayoutDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReimbursementStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportType")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportEmail")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("TotalDevices")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportedFileId");

                    b.ToTable("ImportedReimbursements");
                });

            modelBuilder.Entity("InventoryApi.Models.ImportedReimbursementDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HardwareSerial")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasServicePerTransaction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportedReimbursementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineType")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NetAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ProcessingFee")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("RawAttributesJson")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ServiceFee")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TotalBillableTransactionAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("TotalBillableTransactionCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalExtraCharge")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TotalNotBillableTransactionAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("TotalNotBillableTransactionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VerticalProductTypeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerticalTypeName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportedReimbursementId");

                    b.ToTable("ImportedReimbursementDevices");
                });

            modelBuilder.Entity("InventoryApi.Models.InventoryCostTransitionBaseline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AverageUnitCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("CostSource")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CutoffAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataQualityNote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HomeStockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("InventoryValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("LegacyPhysicalDiscrepancy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LegacyReplayedPhysicalQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MachineStockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpeningCostingQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("InventoryCostTransitionBaselines");
                });

            modelBuilder.Entity("InventoryApi.Models.InventoryCostTransitionMachineStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryCostTransitionBaselineId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MachineName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InventoryCostTransitionBaselineId");

                    b.ToTable("InventoryCostTransitionMachineStocks");
                });

            modelBuilder.Entity("InventoryApi.Models.InventoryCostTransitionPreviewDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InventoryCostTransitionPreviewDrafts");
                });

            modelBuilder.Entity("InventoryApi.Models.NayaxProcessingFeeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FeeExGst")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveFrom")
                        .IsUnique();

                    b.ToTable("NayaxProcessingFeeRates");
                });

            modelBuilder.Entity("InventoryApi.Models.NayaxSales", b =>
                {
                    b.Property<long>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CostOfGoodsSold")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("CostSource")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostingStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MachineAuthorizationTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("MachineID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MachineName")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NayaxProductCostPrice")
                        .HasColumnType("decimal(18,6)");

                    b.Property<long?>("NayaxProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SettlementValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TransactionStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("UnitCostAtSale")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("TransactionID");

                    b.ToTable("NayaxSales", (string)null);
                });

            modelBuilder.Entity("InventoryApi.Models.OperatingExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountExGst")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AttachmentContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachmentFileName")
                        .HasColumnType("TEXT");

                    b.Property<long?>("AttachmentFileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttachmentStoredFileName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GstAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ServicePeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ServicePeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("ExpenseDate");

                    b.HasIndex("MachineId");

                    b.HasIndex("SupplierId");

                    b.ToTable("OperatingExpenses");
                });

            modelBuilder.Entity("InventoryApi.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AverageUnitCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CostingQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InventoryValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("InventoryApi.Models.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DeliveryCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PackageCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("InventoryApi.Models.ReceiptItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("ReceiptItems");
                });

            modelBuilder.Entity("InventoryApi.Models.SiteCommissionAgreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Basis")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CommissionRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaymentDueDaysAfterPeriodEnd")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("SiteCommissionAgreements");
                });

            modelBuilder.Entity("InventoryApi.Models.StockAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AverageUnitCostAfter")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int?>("CostingQuantityAfter")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EatBefore")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InventoryValueAfter")
                        .HasColumnType("decimal(18,6)");

                    b.Property<long?>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReceiptItemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReceiptItemId");

                    b.ToTable("StockAdjustments");
                });

            modelBuilder.Entity("InventoryApi.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("InventoryApi.Models.SupplierOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpectedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId", "Status", "OrderDate");

                    b.ToTable("SupplierOrders");
                });

            modelBuilder.Entity("InventoryApi.Models.SupplierOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuantityOrdered")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("QuantityReceived")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SupplierOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierOrderId");

                    b.HasIndex("ProductId", "SupplierOrderId");

                    b.ToTable("SupplierOrderLines");
                });

            modelBuilder.Entity("InventoryApi.Models.ImportedDevicePayment", b =>
                {
                    b.HasOne("InventoryApi.Models.ImportedReimbursement", "ImportedReimbursement")
                        .WithMany("DevicePayments")
                        .HasForeignKey("ImportedReimbursementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportedReimbursement");
                });

            modelBuilder.Entity("InventoryApi.Models.ImportedFee", b =>
                {
                    b.HasOne("InventoryApi.Models.ImportedReimbursement", "ImportedReimbursement")
                        .WithMany("Fees")
                        .HasForeignKey("ImportedReimbursementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportedReimbursement");
                });

            modelBuilder.Entity("InventoryApi.Models.ImportedPaymentMethod", b =>
                {
                    b.HasOne("InventoryApi.Models.ImportedReimbursement", "ImportedReimbursement")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("ImportedReimbursementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportedReimbursement");
                });

            modelBuilder.Entity("InventoryApi.Models.ImportedReimbursement", b =>
                {
                    b.HasOne("InventoryApi.Models.ImportedFile", "ImportedFile")
                        .WithMany("Reimbursements")
                        .HasForeignKey("ImportedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportedFile");
                });

            modelBuilder.Entity("InventoryApi.Models.ImportedReimbursementDevice", b =>
                {
                    b.HasOne("InventoryApi.Models.ImportedReimbursement", "ImportedReimbursement")
                        .WithMany("Devices")
                        .HasForeignKey("ImportedReimbursementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportedReimbursement");
                });

            modelBuilder.Entity("InventoryApi.Models.InventoryCostTransitionBaseline", b =>
                {
                    b.HasOne("InventoryApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InventoryApi.Models.InventoryCostTransitionMachineStock", b =>
                {
                    b.HasOne("InventoryApi.Models.InventoryCostTransitionBaseline", "InventoryCostTransitionBaseline")
                        .WithMany("MachineStocks")
                        .HasForeignKey("InventoryCostTransitionBaselineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryCostTransitionBaseline");
                });

            modelBuilder.Entity("InventoryApi.Models.OperatingExpense", b =>
                {
                    b.HasOne("InventoryApi.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("InventoryApi.Models.Product", b =>
                {
                    b.HasOne("InventoryApi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InventoryApi.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("InventoryApi.Models.Receipt", b =>
                {
                    b.HasOne("InventoryApi.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("InventoryApi.Models.ReceiptItem", b =>
                {
                    b.HasOne("InventoryApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryApi.Models.Receipt", "Receipt")
                        .WithMany("Items")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("InventoryApi.Models.StockAdjustment", b =>
                {
                    b.HasOne("InventoryApi.Models.Product", "Product")
                        .WithMany("StockAdjustments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryApi.Models.ReceiptItem", "ReceiptItem")
                        .WithMany()
                        .HasForeignKey("ReceiptItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Product");

                    b.Navigation("ReceiptItem");
                });

            modelBuilder.Entity("InventoryApi.Models.SupplierOrder", b =>
                {
                    b.HasOne("InventoryApi.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("InventoryApi.Models.SupplierOrderLine", b =>
                {
                    b.HasOne("InventoryApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryApi.Models.SupplierOrder", "SupplierOrder")
                        .WithMany("Lines")
                        .HasForeignKey("SupplierOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SupplierOrder");
                });

            modelBuilder.Entity("InventoryApi.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("InventoryApi.Models.ImportedFile", b =>
                {
                    b.Navigation("Reimbursements");
                });

            modelBuilder.Entity("InventoryApi.Models.ImportedReimbursement", b =>
                {
                    b.Navigation("DevicePayments");

                    b.Navigation("Devices");

                    b.Navigation("Fees");

                    b.Navigation("PaymentMethods");
                });

            modelBuilder.Entity("InventoryApi.Models.InventoryCostTransitionBaseline", b =>
                {
                    b.Navigation("MachineStocks");
                });

            modelBuilder.Entity("InventoryApi.Models.Product", b =>
                {
                    b.Navigation("StockAdjustments");
                });

            modelBuilder.Entity("InventoryApi.Models.Receipt", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("InventoryApi.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("InventoryApi.Models.SupplierOrder", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
