namespace Inventory.Application.Documents;

/// <summary>
/// The Application layer's port for the bytes of an uploaded business document (issue #39).
///
/// A document's bytes live outside the database, so this port is deliberately narrow. It takes
/// a <see cref="DocumentCategory"/> and the server-generated stored file name already held on
/// the tenant-owned purchase or operating-expense record, and nothing else: no physical path,
/// no container or bucket, no URL, no host environment, and above all no caller-supplied
/// business identifier. Ownership is resolved before a call reaches this port, by loading the
/// parent record through the tenant-filtered <c>AppDbContext</c> - the boundary established by
/// issue #64 - so an adapter can never be asked to read or delete a document on behalf of a
/// business the caller does not belong to.
///
/// Implementations must treat <c>storedFileName</c> as untrusted and confine every operation to
/// the storage they were configured with.
/// </summary>
public interface IDocumentStorage
{
    /// <summary>
    /// Writes a new document. The stored file name is generated by the caller and must not
    /// already exist: implementations must not silently overwrite an existing document, and
    /// must not leave a partially written one behind when the copy fails.
    /// </summary>
    /// <param name="category">Which kind of document is being stored.</param>
    /// <param name="storedFileName">The server-generated name to store the document under.</param>
    /// <param name="content">The document bytes to copy into storage.</param>
    /// <param name="cancellationToken">Cancels the write.</param>
    Task SaveAsync(
        DocumentCategory category,
        string storedFileName,
        Stream content,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Opens a stored document, or returns <c>null</c> when no document is stored under that
    /// name. A missing document is an ordinary result, not an error: the API turns it into the
    /// same <c>404</c> a caller gets for a record it may not see, so absence and refusal are
    /// indistinguishable from outside.
    /// </summary>
    /// <param name="category">Which kind of document to read.</param>
    /// <param name="storedFileName">The stored name held on the tenant-owned parent record.</param>
    /// <param name="cancellationToken">Cancels opening the document.</param>
    Task<DocumentContent?> OpenReadAsync(
        DocumentCategory category,
        string? storedFileName,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Deletes a stored document and reports whether one was there to delete. Callers compose
    /// this with <see cref="SaveAsync"/> to replace a document, and order the two calls around
    /// their own transaction so a failed database write never leaves the wrong bytes behind.
    /// </summary>
    /// <param name="category">Which kind of document to delete.</param>
    /// <param name="storedFileName">The stored name held on the tenant-owned parent record.</param>
    /// <param name="cancellationToken">Cancels the delete.</param>
    Task<bool> DeleteAsync(
        DocumentCategory category,
        string? storedFileName,
        CancellationToken cancellationToken = default);
}
