// <auto-generated />
using System;
using Inventory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261010223128_AddOneActiveMembershipPerIdentity")]
    partial class AddOneActiveMembershipPerIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Inventory.Infrastructure.Models.Business", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.BusinessBackfillAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("RowsAssigned")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalRowsAfter")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalRowsBefore")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnassignedRowsAfter")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnassignedRowsBefore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("BusinessBackfillAudits");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.BusinessMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryTenantId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StatusChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("DirectoryTenantId", "ObjectId");

                    b.HasIndex("DirectoryTenantId", "ObjectId", "BusinessId")
                        .IsUnique();

                    b.HasIndex(new[] { "DirectoryTenantId", "ObjectId" }, "IX_BusinessMemberships_DirectoryTenantId_ObjectId_Active")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = 1");

                    b.ToTable("BusinessMemberships");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.BusinessNayaxConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessTokenCiphertext")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CredentialRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncryptionKeyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastTestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId")
                        .IsUnique();

                    b.ToTable("BusinessNayaxConnections");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("Name");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.CommissionPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<long>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("SiteId", "PeriodStart", "PeriodEnd");

                    b.ToTable("CommissionPayments");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.ImportedDevicePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportedReimbursementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentMethodDescription")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ProcessingFees")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("RawAttributesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecognitionDescription")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SalesCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ServiceFees")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TotalSum")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ImportedReimbursementId");

                    b.ToTable("ImportedDevicePayments");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.ImportedFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AverageFeeAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeeTypeDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeesTypeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportedReimbursementId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPreviousPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsService")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawAttributesJson")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalCount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TotalSum")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TotalSumWithVat")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("VatPercentage")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ImportedReimbursementId");

                    b.ToTable("ImportedFees");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.ImportedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("BusinessId", "FileHash")
                        .IsUnique();

                    b.ToTable("ImportedFiles");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.ImportedPaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BillingProvider")
                        .HasColumnType("TEXT");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportedReimbursementId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNayaxReimbursement")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPreviousPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentMethodDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethodId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawAttributesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecognitionDescription")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalSalesCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalSalesSum")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ImportedReimbursementId");

                    b.ToTable("ImportedPaymentMethods");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.ImportedReimbursement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveDevices")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DistributorActorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErpId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinanceEntityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportedFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvoicePaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoicePaymentMethodId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInvoice")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReimbursement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawAttributesJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReimbursementEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReimbursementPayoutDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReimbursementStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportType")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportEmail")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("TotalDevices")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ImportedFileId");

                    b.ToTable("ImportedReimbursements");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.ImportedReimbursementDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HardwareSerial")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasServicePerTransaction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportedReimbursementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineType")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NetAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ProcessingFee")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("RawAttributesJson")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ServiceFee")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TotalBillableTransactionAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("TotalBillableTransactionCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalExtraCharge")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TotalNotBillableTransactionAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("TotalNotBillableTransactionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VerticalProductTypeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerticalTypeName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ImportedReimbursementId");

                    b.ToTable("ImportedReimbursementDevices");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.InventoryCostRepair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByDirectoryTenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ProductId");

                    b.HasIndex("BusinessId", "ProductId", "EffectiveAt");

                    b.ToTable("InventoryCostRepairs");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.InventoryCostTransitionBaseline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AverageUnitCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostSource")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CutoffAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataQualityNote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HomeStockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("InventoryValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("LegacyPhysicalDiscrepancy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LegacyReplayedPhysicalQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MachineStockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpeningCostingQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ProductId");

                    b.HasIndex("BusinessId", "ProductId")
                        .IsUnique();

                    b.ToTable("InventoryCostTransitionBaselines");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.InventoryCostTransitionMachineStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryCostTransitionBaselineId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MachineName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("InventoryCostTransitionBaselineId");

                    b.ToTable("InventoryCostTransitionMachineStocks");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.InventoryCostTransitionPreviewDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("InventoryCostTransitionPreviewDrafts");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.NayaxMachineStockEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DuplicateResolution")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DuplicateResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventDateTimeGmt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EventDateTimeVmc")
                        .HasColumnType("TEXT");

                    b.Property<long>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatchedManualStockAdjustmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MatchedProductId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NayaxEventLogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NeedsReviewReason")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParsedMdb")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParsedProductName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParsedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawEventData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawSourceMetadata")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StockAdjustmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("MatchedManualStockAdjustmentId");

                    b.HasIndex("MatchedProductId");

                    b.HasIndex("BusinessId", "NayaxEventLogId")
                        .IsUnique();

                    b.HasIndex("BusinessId", "MachineId", "ProcessingStatus");

                    b.ToTable("NayaxMachineStockEvents");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.NayaxProcessingFeeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FeeExGst")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("BusinessId", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("NayaxProcessingFeeRates");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.NayaxSaleTimestampRepair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppliedByDirectoryTenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppliedByObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EvidenceSource")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PreviewId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PreviousBusinessDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PreviousInstantUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RepairedBusinessDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RepairedInstantUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("BusinessId", "TransactionId", "AppliedAt");

                    b.ToTable("NayaxSaleTimestampRepairs");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.NayaxSaleTimestampRepairPreviewDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("NayaxSaleTimestampRepairPreviewDrafts");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.NayaxSales", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CostOfGoodsSold")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("CostSource")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostingStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MachineAuthorizationTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("MachineID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MachineName")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NayaxProductCostPrice")
                        .HasColumnType("decimal(18,6)");

                    b.Property<long?>("NayaxProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SettlementValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("TransactionID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TransactionStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("UnitCostAtSale")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("BusinessId", "TransactionID")
                        .IsUnique();

                    b.ToTable("NayaxSales", (string)null);
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.OperatingExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountExGst")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AttachmentContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachmentFileName")
                        .HasColumnType("TEXT");

                    b.Property<long?>("AttachmentFileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttachmentStoredFileName")
                        .HasColumnType("TEXT");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GstAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ServicePeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ServicePeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("Category");

                    b.HasIndex("ExpenseDate");

                    b.HasIndex("MachineId");

                    b.HasIndex("SupplierId");

                    b.ToTable("OperatingExpenses");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AverageUnitCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CostingQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("GstRule")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("InventoryValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestockTo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DeliveryCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DeliveryGstClassification")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeliveryGstClassificationSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PackageCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PackageGstClassification")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PackageGstClassificationSource")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Receipts", (string)null);
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.PurchaseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GstClassification")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GstClassificationSource")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("ReceiptItems", (string)null);
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.SiteCommissionAgreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Basis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CommissionRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaymentDueDaysAfterPeriodEnd")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("BusinessId", "SiteId", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("SiteCommissionAgreements");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.StockAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AverageUnitCostAfter")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CostingQuantityAfter")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EatBefore")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InventoryValueAfter")
                        .HasColumnType("decimal(18,6)");

                    b.Property<long?>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReceiptItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReceiptItemId");

                    b.ToTable("StockAdjustments");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactName")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryGstDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PackageGstDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductLineGstDefault")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("Name");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.SupplierOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpectedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("SupplierId", "Status", "OrderDate");

                    b.ToTable("SupplierOrders");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.SupplierOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuantityOrdered")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("QuantityReceived")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SupplierOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("SupplierOrderId");

                    b.HasIndex("ProductId", "SupplierOrderId");

                    b.ToTable("SupplierOrderLines");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.SupplierOrderReceiptAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantityApplied")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ReceiptItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplierOrderLineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ReceiptItemId");

                    b.HasIndex("SupplierOrderLineId");

                    b.ToTable("SupplierOrderReceiptAllocations");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.BusinessMembership", b =>
                {
                    b.HasOne("Inventory.Infrastructure.Models.Business", "Business")
                        .WithMany("Memberships")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.ImportedDevicePayment", b =>
                {
                    b.HasOne("Inventory.Infrastructure.Models.ImportedReimbursement", "ImportedReimbursement")
                        .WithMany("DevicePayments")
                        .HasForeignKey("ImportedReimbursementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportedReimbursement");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.ImportedFee", b =>
                {
                    b.HasOne("Inventory.Infrastructure.Models.ImportedReimbursement", "ImportedReimbursement")
                        .WithMany("Fees")
                        .HasForeignKey("ImportedReimbursementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportedReimbursement");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.ImportedPaymentMethod", b =>
                {
                    b.HasOne("Inventory.Infrastructure.Models.ImportedReimbursement", "ImportedReimbursement")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("ImportedReimbursementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportedReimbursement");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.ImportedReimbursement", b =>
                {
                    b.HasOne("Inventory.Infrastructure.Models.ImportedFile", "ImportedFile")
                        .WithMany("Reimbursements")
                        .HasForeignKey("ImportedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportedFile");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.ImportedReimbursementDevice", b =>
                {
                    b.HasOne("Inventory.Infrastructure.Models.ImportedReimbursement", "ImportedReimbursement")
                        .WithMany("Devices")
                        .HasForeignKey("ImportedReimbursementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportedReimbursement");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.InventoryCostRepair", b =>
                {
                    b.HasOne("Inventory.Infrastructure.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.InventoryCostTransitionBaseline", b =>
                {
                    b.HasOne("Inventory.Infrastructure.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.InventoryCostTransitionMachineStock", b =>
                {
                    b.HasOne("Inventory.Infrastructure.Models.InventoryCostTransitionBaseline", "InventoryCostTransitionBaseline")
                        .WithMany("MachineStocks")
                        .HasForeignKey("InventoryCostTransitionBaselineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryCostTransitionBaseline");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.NayaxMachineStockEvent", b =>
                {
                    b.HasOne("Inventory.Infrastructure.Models.StockAdjustment", "MatchedManualStockAdjustment")
                        .WithMany()
                        .HasForeignKey("MatchedManualStockAdjustmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Inventory.Infrastructure.Models.Product", "MatchedProduct")
                        .WithMany()
                        .HasForeignKey("MatchedProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MatchedManualStockAdjustment");

                    b.Navigation("MatchedProduct");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.OperatingExpense", b =>
                {
                    b.HasOne("Inventory.Infrastructure.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.Product", b =>
                {
                    b.HasOne("Inventory.Infrastructure.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Inventory.Infrastructure.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.Purchase", b =>
                {
                    b.HasOne("Inventory.Infrastructure.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.PurchaseItem", b =>
                {
                    b.HasOne("Inventory.Infrastructure.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Inventory.Infrastructure.Models.Purchase", "Purchase")
                        .WithMany("Items")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.StockAdjustment", b =>
                {
                    b.HasOne("Inventory.Infrastructure.Models.Product", "Product")
                        .WithMany("StockAdjustments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory.Infrastructure.Models.PurchaseItem", "ReceiptItem")
                        .WithMany()
                        .HasForeignKey("ReceiptItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Product");

                    b.Navigation("ReceiptItem");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.SupplierOrder", b =>
                {
                    b.HasOne("Inventory.Infrastructure.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.SupplierOrderLine", b =>
                {
                    b.HasOne("Inventory.Infrastructure.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Inventory.Infrastructure.Models.SupplierOrder", "SupplierOrder")
                        .WithMany("Lines")
                        .HasForeignKey("SupplierOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SupplierOrder");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.SupplierOrderReceiptAllocation", b =>
                {
                    b.HasOne("Inventory.Infrastructure.Models.PurchaseItem", "ReceiptItem")
                        .WithMany("SupplierOrderAllocations")
                        .HasForeignKey("ReceiptItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory.Infrastructure.Models.SupplierOrderLine", "SupplierOrderLine")
                        .WithMany("ReceiptAllocations")
                        .HasForeignKey("SupplierOrderLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReceiptItem");

                    b.Navigation("SupplierOrderLine");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.Business", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.ImportedFile", b =>
                {
                    b.Navigation("Reimbursements");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.ImportedReimbursement", b =>
                {
                    b.Navigation("DevicePayments");

                    b.Navigation("Devices");

                    b.Navigation("Fees");

                    b.Navigation("PaymentMethods");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.InventoryCostTransitionBaseline", b =>
                {
                    b.Navigation("MachineStocks");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.Product", b =>
                {
                    b.Navigation("StockAdjustments");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.Purchase", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.PurchaseItem", b =>
                {
                    b.Navigation("SupplierOrderAllocations");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.SupplierOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Inventory.Infrastructure.Models.SupplierOrderLine", b =>
                {
                    b.Navigation("ReceiptAllocations");
                });
#pragma warning restore 612, 618
        }
    }
}
